blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/misitebao/yakia/discussions
    about: If your question is not a feature or a bug, please go to the discussion panel and retrieve if your question already exists before submitting. | 如果您的问题不是功能或者错误，请转到讨论面板并在提交之前检索您的问题是否已经存在。
